service: maiko-linebot

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage}
  region: ap-northeast-1
  memorySize: 128
functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: line
          method: post
