service: maiko-linebot

provider:
  name: aws
  runtime: nodejs4.3
  profile: ${opt:profile, self:custom.defaultProfile}
  stage: ${opt:stage}
  region: ap-northeast-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*

include:
  - lib/**

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: line
          method: post
